fail for anything less than 100% test coverage

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -31,7 +31,13 @@ elif [ ! -f "$DIR/bin/kcov" ]; then
   crystal spec
 # otherwise, run specs with coverage
 else
-  $DIR/bin/crkcov --cleanup-coverage-before --coverage-dir $DIR/coverage --fail-below-low 100 --kcov-executable $DIR/bin/kcov
+  test_output=$($DIR/bin/crkcov --cleanup-coverage-before --coverage-dir $DIR/coverage --kcov-executable $DIR/bin/kcov --output)
+  echo "$test_output"
+  # if the exact string of `Total covored:	100` is not found in the output, the tests failed
+  if [[ $test_output != *"Total covered: 100%"* ]]; then
+    echo -e "❌ ${RED}incomplete test coverage${OFF}"
+    exit 1
+  fi
 fi
 
 echo -e "✅ ${GREEN}tests complete!${OFF}"
